use std::collections::HashSet;
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};

use crc32fast::Hasher;

use crate::data::{RequiredDataFileEntry, ResolvedOpenMwConfig};
use crate::openmw_ini_importer::PluginIndex;

const REQUIRED_DATA_FILES: &str = "requiredDataFiles.json";
const SERVER_DATA_SUBDIR: &str = "server/data";

/// Known-good CRC32 checksums for alternate Morrowind GOTY editions (EN + RU).
const DEFAULT_BASE_ESM_CRCS: &[(&str, &[&str])] = &[
    (
        "morrowind.esm",
        &["0x7B6AF5B9", "0x34282D67"],
    ),
    (
        "tribunal.esm",
        &["0xF481F334", "0x211329EF"],
    ),
    (
        "bloodmoon.esm",
        &["0x43DD2132", "0x9EB62F26"],
    ),
];

const FILE_HEADER: &str = r#"// This file lets you enforce a certain plugin list and order for all clients
// attempting to join this server
//
// Generated by Nerevar from the instance load order and manifest
"#;

pub fn build_required_data_files(resolved: &ResolvedOpenMwConfig) -> Result<Vec<RequiredDataFileEntry>, String> {
    let data_paths = parse_data_paths(&resolved.data_paths);
    let index = PluginIndex::build(&data_paths);
    let mut entries = Vec::new();

    for plugin in &resolved.content {
        let path = resolve_plugin_path(&index, plugin)?;
        let computed = file_crc32_hex(&path)?;
        let checksums = merge_checksums(plugin, computed);
        entries.push(RequiredDataFileEntry {
            file: plugin.clone(),
            checksums,
        });
    }

    Ok(entries)
}

pub fn write_required_data_files(
    tes3mp_dir: &Path,
    entries: &[RequiredDataFileEntry],
) -> Result<PathBuf, String> {
    let data_dir = tes3mp_server_data_dir(tes3mp_dir)?;
    std::fs::create_dir_all(&data_dir)
        .map_err(|e| format!("Failed to create {}: {e}", data_dir.display()))?;

    let path = data_dir.join(REQUIRED_DATA_FILES);
    let json = format_required_data_files_json(entries);
    std::fs::write(&path, json)
        .map_err(|e| format!("Failed to write {}: {e}", path.display()))?;
    Ok(path)
}

pub fn write_required_data_files_for_resolved(
    tes3mp_dir: &Path,
    resolved: &ResolvedOpenMwConfig,
) -> Result<PathBuf, String> {
    let entries = build_required_data_files(resolved)?;
    write_required_data_files(tes3mp_dir, &entries)
}

fn tes3mp_server_data_dir(tes3mp_dir: &Path) -> Result<PathBuf, String> {
    let direct = tes3mp_dir.join(SERVER_DATA_SUBDIR);
    if direct.is_dir() {
        return Ok(direct);
    }

    find_server_data_dir(tes3mp_dir, 5).ok_or_else(|| {
        format!(
            "Could not find {SERVER_DATA_SUBDIR} under {}",
            tes3mp_dir.display()
        )
    })
}

fn find_server_data_dir(dir: &Path, max_depth: u32) -> Option<PathBuf> {
    if max_depth == 0 {
        return None;
    }

    let server_data = dir.join("server/data");
    if server_data.is_dir() {
        return Some(server_data);
    }

    let entries = std::fs::read_dir(dir).ok()?;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if let Some(found) = find_server_data_dir(&path, max_depth - 1) {
                return Some(found);
            }
        }
    }

    None
}

fn parse_data_paths(data_paths: &[String]) -> Vec<PathBuf> {
    data_paths
        .iter()
        .map(|p| PathBuf::from(strip_quotes(p)))
        .collect()
}

fn strip_quotes(path: &str) -> String {
    let trimmed = path.trim();
    trimmed
        .strip_prefix('"')
        .and_then(|s| s.strip_suffix('"'))
        .unwrap_or(trimmed)
        .to_string()
}

/// OpenMW resolves plugins from later `data=` paths first (same as Tes3MpPluginHelper).
fn resolve_plugin_path(index: &PluginIndex, plugin: &str) -> Result<PathBuf, String> {
    index
        .find(plugin)
        .cloned()
        .ok_or_else(|| format!("Plugin not found on disk: {plugin}"))
}

fn file_crc32_hex(path: &Path) -> Result<String, String> {
    let mut file = File::open(path)
        .map_err(|e| format!("Failed to open {}: {e}", path.display()))?;
    let mut hasher = Hasher::new();
    let mut buffer = [0u8; 8192];
    loop {
        let read = file
            .read(&mut buffer)
            .map_err(|e| format!("Failed to read {}: {e}", path.display()))?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
    }
    Ok(format!("0x{:08X}", hasher.finalize()))
}

fn merge_checksums(plugin: &str, computed: String) -> Vec<String> {
    let mut set: HashSet<String> = HashSet::new();
    let lower = plugin.to_ascii_lowercase();

    for (name, defaults) in DEFAULT_BASE_ESM_CRCS {
        if lower == *name {
            for crc in *defaults {
                set.insert((*crc).to_string());
            }
        }
    }

    set.insert(computed);
    let mut checksums: Vec<String> = set.into_iter().collect();
    checksums.sort();
    checksums
}

fn format_required_data_files_json(entries: &[RequiredDataFileEntry]) -> String {
    let mut out = String::from(FILE_HEADER);
    out.push_str("\n[\n");

    for (index, entry) in entries.iter().enumerate() {
        if index > 0 {
            out.push(',');
            out.push('\n');
        }
        let checksums = entry
            .checksums
            .iter()
            .map(|c| format!("\"{c}\""))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    {{\"{}\": [{checksums}]}}", entry.file));
    }

    out.push('\n');
    out.push(']');
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn merge_includes_default_morrowind_crcs() {
        let merged = merge_checksums("Morrowind.esm", "0x7B6AF5B9".to_string());
        assert!(merged.contains(&"0x7B6AF5B9".to_string()));
        assert!(merged.contains(&"0x34282D67".to_string()));
    }

    #[test]
    fn json_format_matches_tes3mp_shape() {
        let json = format_required_data_files_json(&[RequiredDataFileEntry {
            file: "Morrowind.esm".to_string(),
            checksums: vec!["0x7B6AF5B9".to_string(), "0x34282D67".to_string()],
        }]);
        assert!(json.contains("\"Morrowind.esm\""));
        assert!(json.contains("0x7B6AF5B9"));
    }
}
