use std::collections::HashSet;
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};

use crc32fast::Hasher;

use crate::data::{RequiredDataFileEntry, ResolvedOpenMwConfig};
use crate::openmw_ini_importer::PluginIndex;

const REQUIRED_DATA_FILES: &str = "requiredDataFiles.json";
const SERVER_DATA_SUBDIR: &str = "server/data";

/// OpenMW 0.48 introduced `builtin.omwscripts`, which the engine loads
/// implicitly as content entry 0. It appears in no `content=` line — not in the
/// ones Nerevar generates, not in the user's — but TES3MP compares a joining
/// client's plugin list against this file *by index*, so leaving it out shifts
/// every entry by one and rejects every client on a 0.48+ runtime with
/// "Bloodmoon.esm is past the number of plugins used by the server". Only a
/// real game client can surface that, which is what found it (2026-07-30).
const BUILTIN_OMWSCRIPTS: &str = "builtin.omwscripts";

/// First OpenMW release that auto-loads `BUILTIN_OMWSCRIPTS`.
const BUILTIN_OMWSCRIPTS_SINCE: (u32, u32) = (0, 48);

/// Where a TES3MP/OpenMW install records its engine version: first line of
/// `resources/version` (e.g. `0.51.0`), present in full builds and server-only
/// tarballs alike.
const VERSION_FILE: &str = "resources/version";

/// Known-good CRC32 checksums for alternate Morrowind GOTY editions (EN + RU).
const DEFAULT_BASE_ESM_CRCS: &[(&str, &[&str])] = &[
    (
        "morrowind.esm",
        &["0x7B6AF5B9", "0x34282D67"],
    ),
    (
        "tribunal.esm",
        &["0xF481F334", "0x211329EF"],
    ),
    (
        "bloodmoon.esm",
        &["0x43DD2132", "0x9EB62F26"],
    ),
];

const FILE_HEADER: &str = r#"// This file lets you enforce a certain plugin list and order for all clients
// attempting to join this server
//
// Generated by Nerevar from the instance load order and manifest
"#;

/// Builds the plugin list a TES3MP server should require of joining clients.
/// `tes3mp_dir` is the instance's TES3MP directory: the runtime version read
/// from it decides whether `builtin.omwscripts` has to lead the list (see the
/// constant's comment — getting this wrong rejects every client).
pub fn build_required_data_files(
    resolved: &ResolvedOpenMwConfig,
    tes3mp_dir: &Path,
) -> Result<Vec<RequiredDataFileEntry>, String> {
    let data_paths = parse_data_paths(&resolved.data_paths);
    let index = PluginIndex::build(&data_paths);
    let mut entries = Vec::new();

    if runtime_loads_builtin_omwscripts(tes3mp_dir) {
        // No checksum on purpose: the file ships inside the runtime and differs
        // between builds, so pinning a hash would reject compatible clients. An
        // empty list means "any checksum" to TES3MP.
        entries.push(RequiredDataFileEntry {
            file: BUILTIN_OMWSCRIPTS.to_string(),
            checksums: Vec::new(),
        });
    }

    for plugin in &resolved.content {
        let path = resolve_plugin_path(&index, plugin)?;
        let computed = file_crc32_hex(&path)?;
        let checksums = merge_checksums(plugin, computed);
        entries.push(RequiredDataFileEntry {
            file: plugin.clone(),
            checksums,
        });
    }

    Ok(entries)
}

pub fn write_required_data_files(
    tes3mp_dir: &Path,
    entries: &[RequiredDataFileEntry],
) -> Result<PathBuf, String> {
    let data_dir = find_tes3mp_server_data_dir(tes3mp_dir)?;
    std::fs::create_dir_all(&data_dir)
        .map_err(|e| format!("Failed to create {}: {e}", data_dir.display()))?;

    let path = data_dir.join(REQUIRED_DATA_FILES);
    let json = format_required_data_files_json(entries);
    std::fs::write(&path, json)
        .map_err(|e| format!("Failed to write {}: {e}", path.display()))?;
    Ok(path)
}

pub fn write_required_data_files_for_resolved(
    tes3mp_dir: &Path,
    resolved: &ResolvedOpenMwConfig,
) -> Result<PathBuf, String> {
    let entries = build_required_data_files(resolved, tes3mp_dir)?;
    write_required_data_files(tes3mp_dir, &entries)
}

/// Whether this instance's runtime implicitly loads `builtin.omwscripts`.
/// Decided from `resources/version` when the install records one; a runtime that
/// doesn't (an unusual hand-assembled tree) falls back to whether the file is
/// physically there, and failing both is treated as pre-0.48 — the behaviour
/// before this check existed.
fn runtime_loads_builtin_omwscripts(tes3mp_dir: &Path) -> bool {
    match openmw_runtime_version(tes3mp_dir) {
        Some(version) => {
            let loads = version >= BUILTIN_OMWSCRIPTS_SINCE;
            log::info!(
                "Instance runtime is OpenMW {}.{}: {} require {BUILTIN_OMWSCRIPTS} of clients",
                version.0,
                version.1,
                if loads { "will" } else { "will not" }
            );
            loads
        }
        None => {
            let found = find_builtin_omwscripts(tes3mp_dir, 6);
            log::warn!(
                "No {VERSION_FILE} under {}: falling back to searching for {BUILTIN_OMWSCRIPTS} \
                 (found: {found})",
                tes3mp_dir.display()
            );
            found
        }
    }
}

/// `(major, minor)` from the first line of the install's `resources/version`.
pub(crate) fn openmw_runtime_version(tes3mp_dir: &Path) -> Option<(u32, u32)> {
    let path = find_relative_file(tes3mp_dir, VERSION_FILE, 6)?;
    let contents = std::fs::read_to_string(path).ok()?;
    parse_openmw_version(&contents)
}

fn parse_openmw_version(contents: &str) -> Option<(u32, u32)> {
    let line = contents.lines().next()?.trim();
    let mut parts = line.split('.');
    let major = parts.next()?.parse().ok()?;
    let minor = parts.next()?.parse().ok()?;
    Some((major, minor))
}

/// Looks for `<dir>/<relative>` at `dir` and in its subdirectories, bounded by
/// `max_depth` — the same shape as `find_server_data_dir`, because an install
/// can sit any number of levels below the instance's `tes3mp/` directory.
fn find_relative_file(dir: &Path, relative: &str, max_depth: u32) -> Option<PathBuf> {
    if max_depth == 0 {
        return None;
    }

    let direct = dir.join(relative);
    if direct.is_file() {
        return Some(direct);
    }

    for entry in std::fs::read_dir(dir).ok()?.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if let Some(found) = find_relative_file(&path, relative, max_depth - 1) {
                return Some(found);
            }
        }
    }

    None
}

/// Whether the runtime ships `builtin.omwscripts` in any of its VFS resource
/// directories (`resources/vfs`, `resources/vfs-mw`, ...).
fn find_builtin_omwscripts(dir: &Path, max_depth: u32) -> bool {
    if max_depth == 0 {
        return false;
    }

    let Ok(entries) = std::fs::read_dir(dir) else {
        return false;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file() && path.file_name().and_then(|n| n.to_str()) == Some(BUILTIN_OMWSCRIPTS) {
            return true;
        }
        if path.is_dir() && find_builtin_omwscripts(&path, max_depth - 1) {
            return true;
        }
    }

    false
}

pub(crate) fn find_tes3mp_server_data_dir(tes3mp_dir: &Path) -> Result<PathBuf, String> {
    let direct = tes3mp_dir.join(SERVER_DATA_SUBDIR);
    if direct.is_dir() {
        return Ok(direct);
    }

    find_server_data_dir(tes3mp_dir, 5).ok_or_else(|| {
        format!(
            "Could not find {SERVER_DATA_SUBDIR} under {}",
            tes3mp_dir.display()
        )
    })
}

fn find_server_data_dir(dir: &Path, max_depth: u32) -> Option<PathBuf> {
    if max_depth == 0 {
        return None;
    }

    let server_data = dir.join("server/data");
    if server_data.is_dir() {
        return Some(server_data);
    }

    let entries = std::fs::read_dir(dir).ok()?;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if let Some(found) = find_server_data_dir(&path, max_depth - 1) {
                return Some(found);
            }
        }
    }

    None
}

fn parse_data_paths(data_paths: &[String]) -> Vec<PathBuf> {
    data_paths
        .iter()
        .map(|p| PathBuf::from(strip_quotes(p)))
        .collect()
}

fn strip_quotes(path: &str) -> String {
    let trimmed = path.trim();
    trimmed
        .strip_prefix('"')
        .and_then(|s| s.strip_suffix('"'))
        .unwrap_or(trimmed)
        .to_string()
}

/// OpenMW resolves plugins from later `data=` paths first (same as Tes3MpPluginHelper).
fn resolve_plugin_path(index: &PluginIndex, plugin: &str) -> Result<PathBuf, String> {
    index
        .find(plugin)
        .cloned()
        .ok_or_else(|| format!("Plugin not found on disk: {plugin}"))
}

fn file_crc32_hex(path: &Path) -> Result<String, String> {
    let mut file = File::open(path)
        .map_err(|e| format!("Failed to open {}: {e}", path.display()))?;
    let mut hasher = Hasher::new();
    let mut buffer = [0u8; 8192];
    loop {
        let read = file
            .read(&mut buffer)
            .map_err(|e| format!("Failed to read {}: {e}", path.display()))?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
    }
    Ok(format!("0x{:08X}", hasher.finalize()))
}

fn merge_checksums(plugin: &str, computed: String) -> Vec<String> {
    let mut set: HashSet<String> = HashSet::new();
    let lower = plugin.to_ascii_lowercase();

    for (name, defaults) in DEFAULT_BASE_ESM_CRCS {
        if lower == *name {
            for crc in *defaults {
                set.insert((*crc).to_string());
            }
        }
    }

    set.insert(computed);
    let mut checksums: Vec<String> = set.into_iter().collect();
    checksums.sort();
    checksums
}

fn format_required_data_files_json(entries: &[RequiredDataFileEntry]) -> String {
    let mut out = String::from(FILE_HEADER);
    out.push_str("\n[\n");

    for (index, entry) in entries.iter().enumerate() {
        if index > 0 {
            out.push(',');
            out.push('\n');
        }
        let checksums = entry
            .checksums
            .iter()
            .map(|c| format!("\"{c}\""))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    {{\"{}\": [{checksums}]}}", entry.file));
    }

    out.push('\n');
    out.push(']');
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn merge_includes_default_morrowind_crcs() {
        let merged = merge_checksums("Morrowind.esm", "0x7B6AF5B9".to_string());
        assert!(merged.contains(&"0x7B6AF5B9".to_string()));
        assert!(merged.contains(&"0x34282D67".to_string()));
    }

    fn temp_install(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("nerevar-rdf-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        // Nested a level deep, like a real instance: <tes3mp>/TES3MP-server/...
        std::fs::create_dir_all(dir.join("TES3MP-server/resources")).unwrap();
        dir
    }

    #[test]
    fn parses_the_openmw_version_line() {
        assert_eq!(parse_openmw_version("0.51.0\nabc\ndef\n"), Some((0, 51)));
        assert_eq!(parse_openmw_version("0.47.0"), Some((0, 47)));
        assert_eq!(parse_openmw_version("not a version"), None);
        assert_eq!(parse_openmw_version(""), None);
    }

    #[test]
    fn builtin_omwscripts_required_only_on_048_and_newer() {
        let dir = temp_install("048");
        let version = dir.join("TES3MP-server/resources/version");

        std::fs::write(&version, "0.51.0\n").unwrap();
        assert!(runtime_loads_builtin_omwscripts(&dir), "0.51 auto-loads it");

        std::fs::write(&version, "0.47.0\n").unwrap();
        assert!(
            !runtime_loads_builtin_omwscripts(&dir),
            "0.47 has no builtin.omwscripts to load"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn falls_back_to_the_file_when_no_version_is_recorded() {
        let dir = temp_install("fallback");
        assert!(
            !runtime_loads_builtin_omwscripts(&dir),
            "no version and no file: behave like pre-0.48"
        );

        let vfs = dir.join("TES3MP-server/resources/vfs-mw");
        std::fs::create_dir_all(&vfs).unwrap();
        std::fs::write(vfs.join("builtin.omwscripts"), b"").unwrap();
        assert!(runtime_loads_builtin_omwscripts(&dir));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn json_format_matches_tes3mp_shape() {
        let json = format_required_data_files_json(&[RequiredDataFileEntry {
            file: "Morrowind.esm".to_string(),
            checksums: vec!["0x7B6AF5B9".to_string(), "0x34282D67".to_string()],
        }]);
        assert!(json.contains("\"Morrowind.esm\""));
        assert!(json.contains("0x7B6AF5B9"));
    }
}
