// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts from `load-order.json`.
 */
export type AdminLoadOrderSummary = { 
/**
 * Packages in the load order, enabled or not.
 */
entryCount: number, 
/**
 * Plugins that will actually be loaded: enabled plugins inside enabled
 * entries. A plugin left on inside a disabled package does not count.
 */
enabledPluginCount: number, };
