// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminLoadOrderSummary } from "./AdminLoadOrderSummary";
import type { AdminManifestSummary } from "./AdminManifestSummary";
import type { AdminPendingChanges } from "./AdminPendingChanges";

/**
 * The host's state as an admin sees it.
 */
export type AdminStatus = { 
/**
 * Whether an instance is activated for sync hosting right now.
 */
hosting: boolean, instanceId: string | null, 
/**
 * From the manifest, the only place the hosting state records a name.
 */
instanceName: string | null, loadOrder: AdminLoadOrderSummary | null, manifest: AdminManifestSummary | null, 
/**
 * Whether the TES3MP dedicated server is running, or `null` when the
 * embedder supervises no process (the desktop app's server, or a daemon
 * built without a process manager wired into the HTTP context).
 */
tes3mpServerRunning: boolean | null, 
/**
 * Staged, not-yet-applied changes, or `null` when nothing is pending.
 * `null` and an object with empty lists would mean the same thing, so
 * only one of them is ever sent: nothing pending is `null`.
 */
pendingChanges: AdminPendingChanges | null, 
/**
 * Whether a running TES3MP dedicated server is enforcing a plugin list
 * older than the manifest now being served. Set by `POST /admin/apply`,
 * because apply deliberately does not restart the game server; cleared
 * by a restart. `false` on a host that has not applied anything this
 * run, which is also what a host with no game server reports.
 */
tes3mpPluginListStale: boolean, };
