// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the served `manifest.json` says about itself.
 */
export type AdminManifestSummary = { 
/**
 * RFC 3339, as written by the manifest build.
 */
generatedAt: string, 
/**
 * Seconds since `generated_at`, or `null` when it does not parse as
 * RFC 3339 (a hand-edited manifest) or is somehow in the future.
 */
ageSeconds: number | null, };
