// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminLoadOrderSummary } from "./AdminLoadOrderSummary";
import type { AdminManifestSummary } from "./AdminManifestSummary";

/**
 * The host's state as an admin sees it.
 */
export type AdminStatus = { 
/**
 * Whether an instance is activated for sync hosting right now.
 */
hosting: boolean, instanceId: string | null, 
/**
 * From the manifest, the only place the hosting state records a name.
 */
instanceName: string | null, loadOrder: AdminLoadOrderSummary | null, manifest: AdminManifestSummary | null, 
/**
 * Whether the TES3MP dedicated server is running, or `null` when the
 * embedder supervises no process (the desktop app's server, or a daemon
 * built without a process manager wired into the HTTP context).
 */
tes3mpServerRunning: boolean | null, 
/**
 * Staged, not-yet-applied changes. There is no staging area yet, so this
 * is always `null`; `PUT /admin/packages/*` gives it a shape.
 */
pendingChanges: null, };
