// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StagedPackage } from "./StagedPackage";

/**
 * The staging area as `GET /admin/status` reports it.
 */
export type AdminPendingChanges = { 
/**
 * Uploaded packages waiting for apply, by name.
 */
staged: Array<StagedPackage>, 
/**
 * Packages in `data/` marked for deletion at apply.
 */
removals: Array<string>, 
/**
 * Whether a `POST /admin/load-order` is waiting to be written. The order
 * itself is not inlined here — it is as long as the mod list, and
 * `GET /admin/load-order` serves it.
 */
hasLoadOrder: boolean, };
