// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the frontend should offer the user for an available update.
 */
export type AppUpdateAction = "runInstaller" | "openReleasePage";
