// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppUpdateAction } from "./AppUpdateAction";

export type AppUpdateRelease = { id: number, tagName: string, name: string, version: string, body: string, publishedAt: string, htmlUrl: string, 
/**
 * What the frontend should do with this release.
 */
action: AppUpdateAction, 
/**
 * The Windows installer asset, when `action` is `runInstaller`. `None`
 * on every other platform — and on Windows when the release published no
 * installer, which downgrades the action to `openReleasePage` rather than
 * failing the whole check.
 */
installerAssetName?: string | null, installerDownloadUrl?: string | null, };
