// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppUpdateRelease = { id: number, tagName: string, name: string, version: string, body: string, publishedAt: string, htmlUrl: string, installerAssetName: string, installerDownloadUrl: string, };
