// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppUpdateRelease } from "./AppUpdateRelease";

export type AppUpdateStatus = { currentVersion: string, updateAvailable: boolean, latestRelease?: AppUpdateRelease | null, };
