// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeSource } from "./RuntimeSource";

export type InstanceConfig = { id: string, name: string, description: string, path: string, dataDir: string, 
/**
 * Legacy: the `tes3mp/tes3mp` release id an instance was installed
 * from, written by builds that predate `runtime`. Still written
 * alongside `runtime` for `githubRelease` sources so a config this
 * build writes stays readable by those builds; `runtime` is what is
 * read. `load_nerevar_config_at` fills `runtime` from this field when
 * it is absent.
 */
releaseId?: string | null, 
/**
 * Where this instance's TES3MP runtime came from. Absent only in
 * configs written before the field existed, which the loader migrates.
 */
runtime?: RuntimeSource | null, 
/**
 * A runtime this instance's *host operator* advertises to players
 * connecting to it: the client's runtime picker preselects it and says
 * where it came from, and the player is free to change it. Only
 * `RuntimeSource::GithubRelease` is meaningful (see
 * `runtime::normalize_runtime_hint`) — a path on the host's disk means
 * nothing on a player's machine. Absent means "no suggestion", which is
 * what every config written before this field says.
 */
runtimeHint?: RuntimeSource | null, remoteHost?: string | null, remoteSyncPort?: number | null, lastSyncedAt?: string | null, tes3mpServerPort?: number | null, syncPassword?: string | null, };
