// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingValue } from "./SettingValue";
import type { Tes3mpGameSettingEntry } from "./Tes3mpGameSettingEntry";

export type InstanceSettings = { version: number, tes3mpGameSettings: Array<Tes3mpGameSettingEntry>, openmwSettings: { [key in string]: { [key in string]: SettingValue } }, 
/**
 * Extra `key=value` lines appended to `openmw.launch.cfg` (e.g. `groundcover=SomeMod.esp`).
 */
openmwCfgOverrides: Array<string>, 
/**
 * Raw INI text appended to the `settings.cfg` launch overlay (`[Section]` blocks).
 */
openmwSettingsCfgOverrides: string, };
