// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One shared library the loader could not resolve, with the package to
 * install for it on the three distribution families Nerevar's players
 * actually run.
 *
 * Hints are *hints*: a family's package name is stable enough to search for
 * even when the exact binary package carries a version suffix that tracks
 * the distribution release. An unrecognised soname keeps all three `None`
 * rather than being guessed at.
 */
export type MissingLibrary = { 
/**
 * The soname exactly as the loader asked for it, e.g. `libopenal.so.1`.
 */
soname: string, debian: string | null, fedora: string | null, arch: string | null, };
