// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a candidate directory came from, so the player can judge the
 * suggestion instead of being handed a bare path.
 */
export type MorrowindCandidateSource = "steamLibrary" | "gogInstall" | "openmwConfig" | "windowsRegistry";
