// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceConfig } from "./InstanceConfig";

export type NerevarConfig = { onboardingComplete: boolean, ownedInstances: Array<InstanceConfig> | null, syncedInstances: Array<InstanceConfig> | null, rootPath: string | null, syncPort: number, 
/**
 * The Morrowind `Data Files` directory onboarding was pointed at.
 *
 * Written by `config::nerevar_config::set_morrowind_data_files` when the
 * OpenMW scaffold is generated from it, so the path can be re-checked or
 * repaired later instead of surviving only as a `data=` line inside
 * `openmw.nerevar.cfg`. Absent in every config written before the field
 * existed, and omitted again when unset, so an older build reads a config
 * this one wrote unchanged.
 */
morrowindDataFiles?: string | null, 
/**
 * GitHub repositories this player has chosen to trust for TES3MP
 * runtimes, as lower-cased `owner/name`, on top of
 * `runtime::trust::BUILTIN_TRUSTED_RUNTIME_REPOS`.
 *
 * A server can pin the *version* it needs but never the repository, so
 * this list is the only thing that widens where Nerevar will download an
 * executable from — see `runtime::trust`. Absent in every config written
 * before the field existed, and omitted again when empty, so an older
 * build reads a config this one wrote unchanged.
 */
trustedRuntimeRepos?: Array<string>, };
