// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeSource } from "./RuntimeSource";

export type NewConnectionConfig = { runtime: RuntimeSource, connectionName: string, connectionDescription: string, instanceRootPath: string, instanceDataDir: string, remoteHost: string, remoteSyncPort: number, syncPassword: string, };
