// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeSource } from "./RuntimeSource";

export type NewConnectionConfig = { runtime: RuntimeSource, connectionName: string, connectionDescription: string, 
/**
 * The Nerevar data directory the instance is created under. The
 * instance's own directories are derived from this and the connection
 * name by `instance_setup::instance_paths`, on the backend, because
 * only it knows the platform's path separator.
 */
rootPath: string, remoteHost: string, remoteSyncPort: number, syncPassword: string, };
