// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The asset file names a host names for the platforms its players run on.
 *
 * The selection rules in [`crate::runtime::select_tes3mp_asset`] are written
 * for the official TES3MP asset names; a fork that names its release files
 * its own way matches none of them. This map is the host's way to say which
 * file *is* the runtime on each platform. It lives beside the hint's
 * [`RuntimeSource`] rather than inside it: a client stores the source it
 * resolved, and the two names it will never use have no business in that
 * record.
 *
 * Every entry is optional and an absent one means "use the naming rule", so
 * an empty map is exactly today's behaviour and is omitted from the JSON.
 */
export type PlatformAssets = { 
/**
 * The asset that is the Windows build.
 */
windows?: string | null, 
/**
 * The asset that is the Linux build.
 */
linux?: string | null, 
/**
 * The asset that is the macOS build.
 */
macos?: string | null, };
