// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemotePackageSummary } from "./RemotePackageSummary";
import type { RuntimeSource } from "./RuntimeSource";

export type RemoteManifestSummary = { instanceId: string, instanceName: string, totalDownloadBytes: number, packageCount: number, tes3mpServerPort: number, passwordRequired: boolean, packages: Array<RemotePackageSummary>, 
/**
 * The TES3MP runtime the host suggests to players (always a
 * `githubRelease`, see `InstanceConfig::runtime_hint`). `None` when the
 * host advertises nothing — which is also what a host older than the
 * field sends, since it simply omits it.
 */
runtimeHint?: RuntimeSource | null, };
