// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolvedOpenMwConfig = { encoding: string, dataPaths: Array<string>, 
/**
 * `content=` lines: `.esm`/`.esp`/`.omwaddon`/`.omwscripts`, never an archive.
 */
content: Array<string>, 
/**
 * `fallback-archive=` lines: the enabled packages' `.bsa` files in
 * package priority order. OpenMW finds each by name in the `data=`
 * directories. The base game's archives are never listed here; the
 * player's own config registers them. Absent in manifests from hosts
 * that predate the field.
 */
archives: Array<string>, };
