// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteManifestSummary } from "./RemoteManifestSummary";

/**
 * A host address that answered, plus the summary it served.
 */
export type ResolvedAddress = { 
/**
 * The address to store and use from now on: the one that was typed, or
 * `https://{host}` when only the HTTPS retry answered.
 */
host: string, summary: RemoteManifestSummary, };
