// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A host requiring a TES3MP version this instance does not have installed.
 */
export type RuntimeMismatch = { instanceId: string, 
/**
 * The tag the host asks for.
 */
requiredTag: string, 
/**
 * The tag of the runtime this instance has. Empty when the instance's
 * runtime is not a GitHub release, or was installed by a build that did
 * not record the tag.
 */
installedTag: string, 
/**
 * The repository an update would be fetched from: the instance's own,
 * which the player chose. Never the hinted one on the strength of the
 * hint alone.
 */
repo: string, 
/**
 * Whether this blocks launching. False when there is nothing to compare —
 * a local-directory or archive runtime, or an instance with no recorded
 * source — in which case the mismatch is reported and nothing else.
 */
enforced: boolean, 
/**
 * The repository the host named, which may not be `repo`.
 */
hintRepo: string, 
/**
 * Whether the player trusts `hint_repo`.
 */
hintRepoTrusted: boolean, 
/**
 * The whole thing in one sentence, so the app, the CLI and the daemon
 * say the same words.
 */
message: string, };
