// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the TES3MP runtime for an instance is fetched from.
 *
 * Serialized as an internally tagged enum (`{"kind": "githubRelease", ...}`)
 * so later variants — `localDirectory { path }`, `archive { path }` — can be
 * added without touching config files already on disk: an old file only ever
 * holds `githubRelease`, and a reader that predates a variant simply fails on
 * that one instance rather than on the whole config.
 */
export type RuntimeSource = { "kind": "githubRelease", 
/**
 * `owner/name`, e.g. `tes3mp/tes3mp`.
 */
repo: string, 
/**
 * The release's numeric GitHub id, as a string (that is how the
 * legacy `InstanceConfig::release_id` stored it).
 */
releaseId: string, 
/**
 * The release's tag (`tes3mp-0.8.1`). Empty when unknown — it is
 * descriptive only; `release_id` is what resolves the release.
 */
tag: string, 
/**
 * The exact asset file name to download. Empty means "let the
 * platform rules pick", which is what the app sends: the selection
 * rules live in core, not in the picker.
 */
assetName: string, };
