// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a host's runtime suggestion means for this client's picker.
 */
export type RuntimeHintResolution = { "status": "noHint" } | { "status": "trusted", repo: string, tag: string, releaseId: string, } | { "status": "untrusted", 
/**
 * What the host named, for the message and nothing else.
 */
repo: string, tag: string, 
/**
 * What the picker is set to instead.
 */
fallbackRepo: string, message: string, };
