// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the UI renders for a runtime source it can check before installing.
 *
 * `missing` empty is the whole test: a source with nothing missing installs,
 * one with entries listed there is not a TES3MP runtime and the create form
 * stays invalid until the user picks something else.
 */
export type RuntimeInspection = { 
/**
 * What was inspected: the directory, or the archive file.
 */
root: string, 
/**
 * `0.48`-style engine version, or `unknown`.
 */
versionDisplay: string, hasClientExe: boolean, hasServerExe: boolean, 
/**
 * Required pieces that are absent, named the way a user would recognize
 * them. Empty means the source is usable.
 */
missing: Array<string>, 
/**
 * Non-fatal observations — a server-only build, an unknown engine
 * version.
 */
warnings: Array<string>, };
