// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlatformAssets } from "./PlatformAssets";

/**
 * The runtime a host advertises to the players who connect to it.
 *
 * A [`RuntimeSource`] — always a `githubRelease`, see
 * [`normalize_runtime_hint`] — plus the per-platform asset names the host
 * wants used instead of the naming rules. Serialized flat
 * (`{"kind": "githubRelease", "repo": ..., "platformAssets": {...}}`), so a
 * hint written before this type existed reads unchanged and a hint with no
 * platform assets writes exactly the JSON it always did.
 */
export type RuntimeHint = { 
/**
 * The asset each platform should download, when the naming rules do not
 * fit this repository's releases. Absent for every hint that does.
 */
platformAssets?: PlatformAssets, } & ({ "kind": "githubRelease", 
/**
 * `owner/name`, e.g. `tes3mp/tes3mp`.
 */
repo: string, 
/**
 * The release's numeric GitHub id, as a string (that is how the
 * legacy `InstanceConfig::release_id` stored it).
 */
releaseId: string, 
/**
 * The release's tag (`tes3mp-0.8.1`). Empty when unknown — it is
 * descriptive only; `release_id` is what resolves the release.
 */
tag: string, 
/**
 * The exact asset file name to download. Empty means "let the
 * platform rules pick", which is what the app sends: the selection
 * rules live in core, not in the picker.
 */
assetName: string, } | { "kind": "localDirectory", 
/**
 * Absolute path to the runtime root (the directory holding the
 * `tes3mp` wrapper, or one holding the release's own top-level
 * directory — inspection recurses either way).
 */
path: string, } | { "kind": "archive", 
/**
 * Absolute path to the archive file.
 */
path: string, });
