// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingLibrary } from "./MissingLibrary";
import type { RuntimeHealthStatus } from "./RuntimeHealthStatus";

/**
 * The result of a runtime health check.
 */
export type RuntimeHealth = { status: RuntimeHealthStatus, 
/**
 * The version line the client printed, when it printed one.
 */
version: string | null, 
/**
 * Why the check failed, or why it was not run. `None` when healthy.
 */
reason: string | null, 
/**
 * What the client (or `ldd`) actually printed, truncated. `None` when
 * healthy — nobody needs the version banner twice.
 */
output: string | null, 
/**
 * Sonames the loader could not resolve, with package hints.
 */
missingLibraries: Array<MissingLibrary>, 
/**
 * Symbol versions this build needs that the system's glibc does not
 * provide, e.g. `GLIBC_2.38`. A too-old glibc is not a missing package
 * and must not be reported as one — there is nothing to install.
 */
glibcRequirements: Array<string>, 
/**
 * The executable that was probed, when one was found.
 */
checkedExecutable: string | null, };
