// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the TES3MP runtime for an instance is fetched from.
 *
 * Serialized as an internally tagged enum (`{"kind": "githubRelease", ...}`)
 * so a new variant never disturbs config files already on disk: a file
 * written before `localDirectory`/`archive` existed only ever holds
 * `githubRelease`, and a reader that predates a variant fails on that one
 * instance rather than on the whole config.
 *
 * Every variant installs *into* the instance's `tes3mp/` directory. Nothing
 * is ever run in place: Nerevar patches the cfgs and `requiredDataFiles.json`
 * inside the install and deletes it with the instance, so a local directory
 * or archive is a template to copy from, not a runtime to borrow.
 */
export type RuntimeSource = { "kind": "githubRelease", 
/**
 * `owner/name`, e.g. `tes3mp/tes3mp`.
 */
repo: string, 
/**
 * The release's numeric GitHub id, as a string (that is how the
 * legacy `InstanceConfig::release_id` stored it).
 */
releaseId: string, 
/**
 * The release's tag (`tes3mp-0.8.1`). Empty when unknown — it is
 * descriptive only; `release_id` is what resolves the release.
 */
tag: string, 
/**
 * The exact asset file name to download. Empty means "let the
 * platform rules pick", which is what the app sends: the selection
 * rules live in core, not in the picker.
 */
assetName: string, } | { "kind": "localDirectory", 
/**
 * Absolute path to the runtime root (the directory holding the
 * `tes3mp` wrapper, or one holding the release's own top-level
 * directory — inspection recurses either way).
 */
path: string, } | { "kind": "archive", 
/**
 * Absolute path to the archive file.
 */
path: string, };
