// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the health check concluded.
 */
export type RuntimeHealthStatus = "healthy" | "failed" | "notChecked";
