// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageKind } from "./PackageKind";

/**
 * One uploaded package waiting for apply.
 */
export type StagedPackage = { 
/**
 * The directory name it will take in `data/`.
 */
name: string, 
/**
 * Mod or Replacer, from the same classification the data-dir scan uses.
 */
kind: PackageKind, 
/**
 * Plugin files found anywhere in the extracted tree, scan's ordering.
 */
plugins: Array<string>, 
/**
 * Whether `data/<name>/` already exists, i.e. whether apply replaces a
 * package rather than adding one. Recorded at upload time; both
 * `GET /admin/status` and the apply planner recompute it against `data/`
 * as it stands, because a package can appear or vanish in between.
 */
replacesExisting: boolean, 
/**
 * Bytes received in the request body (the archive).
 */
archiveBytes: number, 
/**
 * Bytes of the extracted tree, which is what apply moves into `data/`.
 */
extractedBytes: number, 
/**
 * RFC 3339, UTC.
 */
stagedAt: string, 
/**
 * Which co-admin uploaded it, for `GET /admin/status`.
 */
stagedBy: string, };
