// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncPhase } from "./SyncPhase";

export type SyncProgressEvent = { instanceId: string, phase: SyncPhase, message: string, bytesDone: number, bytesTotal: number, filesDone: number, filesTotal: number, overallPercent: number, currentFile: string | null, };
