// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestValidationResult } from "./ManifestValidationResult";
import type { RuntimeMismatch } from "./RuntimeMismatch";

/**
 * Everything a completed sync has to say.
 *
 * The file check is the sync's own verdict; the runtime mismatch is the
 * host's version requirement measured against what this instance has
 * installed, which a caller acts on separately — the app blocks the launch
 * and offers the update, the CLI exits non-zero for `--launch`.
 */
export type SyncOutcome = { validation: ManifestValidationResult, 
/**
 * `None` when the host requires no particular TES3MP version, or when
 * the installed runtime already satisfies the one it requires.
 */
runtimeMismatch?: RuntimeMismatch | null, };
