// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingValue } from "./SettingValue";

export type Tes3mpGameSettingEntry = { name: string, value: SettingValue, };
