// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the trusted-source list as a settings screen shows it.
 */
export type TrustedRepo = { 
/**
 * `owner/name`, lower-cased.
 */
repo: string, 
/**
 * True for [`BUILTIN_TRUSTED_RUNTIME_REPOS`], which cannot be removed.
 */
builtin: boolean, };
