// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceConfig = { id: string, name: string, description: string, path: string, dataDir: string, releaseId?: string | null, remoteHost?: string | null, remoteSyncPort?: number | null, lastSyncedAt?: string | null, tes3mpServerPort?: number | null, syncPassword?: string | null, };
