// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Mo2ModlistImportReport = { matchedMods: number, disabledMods: number, missingModDirectories: Array<string>, missingPlugins: Array<string>, importedPlugins: number, };
