// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewConnectionConfig = { releaseId: string, connectionName: string, connectionDescription: string, instanceRootPath: string, instanceDataDir: string, remoteHost: string, remoteSyncPort: number, syncPassword: string, };
