// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemotePackageSummary } from "./RemotePackageSummary";

export type RemoteManifestSummary = { instanceId: string, instanceName: string, totalDownloadBytes: bigint, packageCount: number, tes3mpServerPort: number, passwordRequired: boolean, packages: Array<RemotePackageSummary>, };
