// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageKind } from "./PackageKind";

export type ScannedPackage = { name: string, kind: PackageKind, relativeDir: string, plugins: Array<string>, treeChecksum: string | null, };
