// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingCategory } from "./SettingCategory";
import type { SettingValue } from "./SettingValue";
import type { SettingValueType } from "./SettingValueType";

export type SettingDefinition = { key: string, category: SettingCategory, valueType: SettingValueType, label: string, description: string, defaultValue: SettingValue, minInteger?: number, maxInteger?: number, };
