// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncPhase } from "./SyncPhase";

export type SyncProgressEvent = { instanceId: string, phase: SyncPhase, message: string, bytesDone: bigint, bytesTotal: bigint, filesDone: bigint, filesTotal: bigint, overallPercent: number, currentFile: string | null, };
